### ISSUE TITLE
Add func like StructFieldFromJSONName but returns a reflect.Value

### ISSUE THREAD

**Issue by dolmen** [lestrrat-go/structinfo#1]
StructFieldFromJSONName is useful, but even more useful would be a func that directly returns the settable reflect.Value of the field.

**Comment by lestrrat** [comment]
@dolmen let me know if this is what you want ? :)

And boy, my old Go code looked ugly. Good riddance.

**Comment by dolmen** [comment]
Godoc is [here](https://pkg.go.dev/github.com/lestrrat-go/structinfo@v0.0.0-20190927032347-f465a1051f17).

**Comment by dolmen** [comment]
Here is a failing test ([see on the Go playground](https://play.golang.org/p/loTJI3YJpcX)). Am I misusing the API?
```go
func ExampleStore_FieldValue() {
	var x struct {
		Name string `json:"name"`
	}

	nameVal, err := structinfo.DefaultStore.FieldValue(reflect.ValueOf(&x), "name")
	if err != nil {
		log.Fatal(err)
	}

	nameVal.SetString("foo")

	fmt.Println(x.Name)

	// Output:
	// foo
}
```

**Comment by lestrrat** [comment]
Wow. This is ancient. let me refresh my memory first...

**Comment by lestrrat** [comment]
@dolmen try acd5187?

**Comment by dolmen** [comment]
You mean 642f549265566c7baa90329c8fe2d36e5b115ddb on branch topic/gh-issue-1?

Indeed, `v0.0.0-20210127220041-642f54926556` fixed it as [shown on the Go playground](https://play.golang.org/p/jZBfb7cjSgI).
🎉
